from fastapi import APIRouter, HTTPException, Body
from google.oauth2 import id_token
from google.auth.transport import requests
from utils.jwt_handler import create_jwt
import os
from dotenv import load_dotenv
from supabase import create_client
import firebase_admin
from firebase_admin import credentials, auth

router = APIRouter(prefix="/api/auth/google", tags=["google"])


# Initialize Firebase Admin
cred = credentials.Certificate(
    "credential/livewell-app-b23a0-firebase-adminsdk-fbsvc-37fd03a6f7.json"
)
firebase_admin.initialize_app(cred)

load_dotenv()


@router.post("")
async def google_auth(token: str = Body(..., embed=True)):
    """
    Verifies the Google ID token and use it to look up for the uuid in firebase.

    Args: The client sends { "token": "google id token" }
    Returns: jwt token to access the backend
    """
    try:
        # Verify Google ID Token
        id_info = id_token.verify_oauth2_token(
            token, requests.Request(), clock_skew_in_seconds=10
        )

        # Get user's google email and name
        # Use email to look up user in Firebase
        email = id_info.get("email")

        # Use name or given name to insert to the database
        user_name = id_info.get("name") or id_info.get("given_name")

        try:
            # Look up the user in Firebase by email to get their Firebase UID
            firebase_user = auth.get_user_by_email(email)
            firebase_uid = firebase_user.uid
        except Exception as e:
            # Expected error will never happen
            print(f"Error fetching Firebase user: {e}")

            raise HTTPException(
                status_code=400, detail="User not found in Firebase system."
            )

        # Using Supabase Admin to bypass Provider check and ensure UID sync
        supabase_admin = create_client(
            supabase_url=os.getenv("SUPABASE_URL"),
            supabase_key=os.getenv("SUPABASE_SERVICE_ROLE_KEY"),
        )

        # Check if the user already exists in your database
        result = (
            supabase_admin.table("profiles")
            .select("*")
            .eq("google_uid", firebase_uid)
            .execute()
        )

        user_id = None

        # User exists, get user id for jwt
        if result.data:
            user = result.data[0]
            user_id = user["id"]

        # User doesn't exist - create new user
        else:
            try:
                # Create user in Supabase Auth
                # Supabase will generate a UUID for the user
                attributes = {
                    "email": email,
                    "email_confirm": True,
                    "user_metadata": {"full_name": user_name},
                }

                auth_user = supabase_admin.auth.admin.create_user(attributes)
                user_id = auth_user.user.id
            except Exception as e:
                print(f"Supabase Auth User creation note: {e}")

                raise HTTPException(
                    status_code=500, detail=f"Failed to create auth user: {str(e)}"
                )

            # Insert into profiles
            # id generated by supabase
            # google_uid is user's uid in firebase
            new_user = (
                supabase_admin.table("profiles")
                .insert(
                    {
                        "id": user_id,
                        "google_uid": firebase_uid,
                        "email": email,
                        "user_name": user_name,
                    }
                )
                .execute()
            )

        # Generate a JWT for the user to authenticate with your backend
        if not user_id:
            raise Exception("Failed to obtain user ID")

        jwt_response = create_jwt(user_id, email)

        return {"token": jwt_response}

    except ValueError as e:
        # Invalid token
        raise HTTPException(status_code=401, detail=f"Invalid Google Token: {str(e)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Authentication error: {str(e)}")
