// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRwePUOmqCLFF90w5R_89RMbNwdUNfd4',
    appId: '1:575568014301:web:21e76c51798b84d5a76434',
    messagingSenderId: '575568014301',
    projectId: 'livewell-app-b23a0',
    authDomain: 'livewell-app-b23a0.firebaseapp.com',
    storageBucket: 'livewell-app-b23a0.firebasestorage.app',
    measurementId: 'G-5ME4D4ZZDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVfJmycsqf3DrH09hyTb18nkKi1ChOYhY',
    appId: '1:575568014301:android:98621a141da3753ea76434',
    messagingSenderId: '575568014301',
    projectId: 'livewell-app-b23a0',
    storageBucket: 'livewell-app-b23a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcgZvGS2yHyMK8GCnZzEEod2x-Ggzu9c',
    appId: '1:575568014301:ios:dfca369a9fa7e31fa76434',
    messagingSenderId: '575568014301',
    projectId: 'livewell-app-b23a0',
    storageBucket: 'livewell-app-b23a0.firebasestorage.app',
    iosBundleId: 'com.example.livewellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcgZvGS2yHyMK8GCnZzEEod2x-Ggzu9c',
    appId: '1:575568014301:ios:dfca369a9fa7e31fa76434',
    messagingSenderId: '575568014301',
    projectId: 'livewell-app-b23a0',
    storageBucket: 'livewell-app-b23a0.firebasestorage.app',
    iosBundleId: 'com.example.livewellApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDRwePUOmqCLFF90w5R_89RMbNwdUNfd4',
    appId: '1:575568014301:web:236d344804d616baa76434',
    messagingSenderId: '575568014301',
    projectId: 'livewell-app-b23a0',
    authDomain: 'livewell-app-b23a0.firebaseapp.com',
    storageBucket: 'livewell-app-b23a0.firebasestorage.app',
    measurementId: 'G-9K9CTB7ZL0',
  );
}
